---
extends: eslint:recommended
root: true
env:
  browser: true
  es6: true
  node: true
globals:
  Drupal: true
  drupalSettings: true
  drupalTranslations: true
  jQuery: true
overrides:
- files:
  - gulpfile.js
  - tasks/**/*.js
  env:
    node: true
rules:
  indent:
  - error
  - 2
  - SwitchCase: 1
  quotes:
  - error
  - single
  linebreak-style:
  - error
  - unix
  semi:
  - error
  - always
  camelcase: error
  eqeqeq: error
  strict:
  - error
  - safe
  no-undef: error
  max-len:
  - error
  - ignoreUrls: true
    ignoreStrings: true
    ignoreRegExpLiterals: true
    ignoreTemplateLiterals: true
  new-cap: error
  no-unused-vars: warn
  one-var:
  - error
  - never
  brace-style:
  - error
  - stroustrup
  valid-jsdoc: error
  block-scoped-var: warn
  curly: error
  no-alert: warn
  no-eval: error
  no-implicit-coercion: error
  no-loop-func: error
  no-script-url: error
  no-sequences: error
  no-useless-concat: error
  no-use-before-define: error
  eol-last: error
  no-trailing-spaces: error
  no-underscore-dangle: error
  require-jsdoc: error
  space-before-blocks: error
  yoda: error
