extends:
  - stylelint-config-standard
plugins:
rules:
  at-rule-no-unknown:
    - true
    - ignoreAtRules:
      - "mixin"
      - "include"
  block-closing-brace-newline-before: always
  block-no-empty: true
  block-opening-brace-newline-after: always
  color-function-notation: null
  color-no-invalid-hex: true
  comment-no-empty: true
  declaration-block-no-redundant-longhand-properties: null
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: never-single-line
  declaration-block-semicolon-space-before: never
  declaration-empty-line-before: never
  font-family-no-duplicate-names: true
  function-calc-no-unspaced-operator: true
  function-comma-space-after: always
  function-linear-gradient-no-nonstandard-direction: true
  function-parentheses-space-inside: never
  hue-degree-notation: number
  keyframe-declaration-no-important: true
  max-line-length:
    - 255
    - ignore:
      - "non-comments"
  media-feature-name-no-unknown: true
  no-descending-specificity: null
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-empty-source: null
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  property-no-unknown: true
  selector-class-pattern: null
  selector-pseudo-class-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-type-no-unknown: true
  string-quotes: single
  string-no-newline: true
  unit-no-unknown: true
  value-list-comma-newline-before: never-multi-line
  value-keyword-case:
    - lower
    - ignoreProperties:
      - "--font-sans"
      - "--font-serif"
      - "--font-system"
      - "--font-mono"

  declaration-property-value-disallowed-list:
    //bborder\b/:
      - none
  declaration-block-no-duplicate-properties:
    - true
    - ignore:
        - consecutive-duplicates-with-different-values
